language: rust
cache: cargo
matrix:
  include:
    - rust: stable
      env: TARGET=fmt
      before_install:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check
    - rust: stable
      script:
        - cargo build --verbose
        - cargo test --verbose
    - rust: beta
      script:
        - cargo build --verbose
        - cargo test --verbose
    - rust: nightly
      script:
        - cargo build --verbose
        - cargo test --verbose
        - cargo bench --verbose
  allow_failures:
    - env: TARGET=fmt
    - rust: nightly
  fast_finish: true
notifications:
  email: false
